# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e077073c4f9314f7fa68a30b007783a1e170a9527de0e89c60308dbacb0b26a58854f04c8df14169f47de2f3679b09644228f80b7ef5823096481cbb85d0344f

test:
  secret_key_base: abbf6213939d2c3daaa260a687c9a64ee31a7f504db4b97e3462eb4afcbf54be0504db52877b02bf34182ea5e9798ebc0c8ccdcc03be6bb4e2e5e54a645ff281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
